spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
  rsa:
    privateKeyPath: src/main/resources/keys/private.pem
    publicKeyPath: src/main/resources/keys/public.pem

