spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://dpg-d2jl8o8gjchc73cnrlt0-a.frankfurt-postgres.render.com:5432/project_postgress
    username: asya_67
    password: k8RQjzlEHW8ySvG1heHOK5ZFfjAF06XX
    driver-class-name: org.postgresql.Driver
